branches:
  only:
  - enable_travis
  - master
  - release
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
matrix:
  include:
  - language: android
    sudo: required
    jdk: oraclejdk8
    before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
    cache:
      directories:
      - "$HOME/.gradle"
      - "$HOME/.android"
      - ".gradle"
    before_install:
    - openssl aes-256-cbc -K $encrypted_1701aaafcc71_key -iv $encrypted_1701aaafcc71_iv -in .travis/android/google-services.json.enc -out frontend/android/google-services.json -d
    - "./.travis/android/before_install.bash"
    android:
      components:
      - platform-tools
      - android-28
      - build-tools-28.0.3
      - extra-google-m2repository
      - extra-android-m2repository
      - tools
      licenses:
      - android-sdk-preview-license-.+
      - android-sdk-license-.+
      - google-gdk-license-.+
    script: ".travis/android/run.bash"
  - language: objective-c
    os: osx
    osx_image: xcode10.1
    xcode_workspace: frontend/ios/DroidKaigi\ 2019.xcworkspace
    cache:
    - directories:
      - ios/frontend/vendor/bundle
      - ios/frontend/Pods
      - "$HOME/.gradle"
      - "$HOME/.android"
      - ".gradle"
      - "$ANDROID_HOME"
    env:
    - ANDROID_HOME="$HOME/android-sdk"
    before_install:
    - "./.travis/ios/before_install.bash"
    script: ".travis/ios/run.bash"
env:
  global:
  - secure: pK1VoGo+Iy0Bff2l7b6O5Z/J4zRTbQgs2D5dUo0j7BnaL9jmwJNpoUbVQmr5dA1Xza2sT6Y1f9GCCh4KazsZj74AAXooVGT8ln3CcdzJBb22k5UwfaLSxDRadzZFE7XxBkhE4e5k+2tel5lZB4HLUyLAVCO15VN3m/EkmsjYzTg6ndhYpYSbYAn8Cfva57798s++8H82WBscIII04RLrbDP/fo6JbUXJAJYY9T8aLzStAU9X8GSyoMzhVlzOLJRTcVsHhpK4pieLuE5ca78ymkEO1pS2mgdfKqdJVgKhcOkXyI4cim0ZYyvJksrXD8JQrsXtv1iSF8Ei1sMrRVGuIN2cbHZdnpKXX2eJS3zS3AEXXXWmEnXhMMH00oxnN1jfa/6/0oTdNV6wmjwinP93xn3zQxdELFawElBL4RxR528T8030MWYapUjvuuHXGU0rXpPeBjANfk1NPCM55x0WXrOx4xO2FdEMjjqCukE/adbMiRYIesa2r9FE7DwMZ/i4BQBRoL+t18Ut/uragXIPSJSannBD3JiDmh23gXWtuPMu2JssYxN5qgNe7yf0crAKeH46rFVA3dZM/cXtJiZ0Id60zXXO775DybIVvGi3vRyTeG1nDD1BpS+t1YswNUM4oyd057MEFsZlV625nBIEInGugaVYkTEbqjSinqb+YS0=
  - secure: D/bT5UGshwtqXps2Jmaq/JJETlCKYvEQwvmHAoqd7WkSTCh/dpZ0Cg2WAtVplDwTOLft4+c3lc/HaTMxCjEs44MnEJaRqCp2Itu6o1BlyaG1+rVuRWe8UFDpHom789mO39NdNGfS/3C4vUAKSKgmG3iU4fWX8JT5UBZCgWFRquQxZWEWk/O8KZ+k2ixuDJmMw4gPZ58jVNDzQwI19gDWKVXSft3a8E6qNSx2aq3GIa71mf2HJNAyHL7MBA8tf/3jS5scc5wVZptnjWlEpEWHiM30AaE3/AtHQgp3J5MT6euEID4onbZWAGe9L64LzkGxjtmeE9x1M51KBeUOtxRCM2zCG2tuekum/SiMeVhIY5scZ5DmaVGzb25pUaxbebHq0h7MmliCC+QMV1PDpNIJstjB5/s2NgisRTg200dqIXS63ov5olFiHoAWIEKK08z42Aiwzq90JeZ0bU6IkBND4WCqo52mdqN7pGLHnlRRT/LeRpciT2XN+1GC4u2WR0Islkqry5XMxI6WCkPYnXBjk8pLmXkbYlffZbGRe8icpdPNa/IqHQIha/fB+abdCRhMm+3uZPzPSC+UJBSKWloHdN2q0GLtKku8uEHDyiRWaXYm+ZAarhsS1mJzg65gogEBpi1fJrZUY586bNJj8xmKMR8gaXljc/lDD8zulDvCdWI=
  - secure: WaV6+r0/iE0MYpAXa31dqLydcIgcjQpodx2c1wbkZv6GjRBcrOiq94xJr4Mo7Rpctwzvw9JIG362QdyOws3Z7x5UTDL0pOyj+hOl0iTPl6Gqp8wOX9KcO9hIgyuYlce0CWY4uW7URlRXO7/4cuo4Ajn5MGx7n0X+Akte37654RBtfwKfBNpn0+K2nXAV4crPXv+zMZHxn4TDXrk6E8L9pPlLSVGkiAxDPujiKK3v7sCno+DtSok2qP3M+U6TJHSw4bRPyxCE9JrJy+4abTRAhwXt5w9izL4ZKPFNqZH56ubHF/Te0CdiSpKSU1btNCfU2fjLEeUpqhVf3ngzHcBINetfFL3Md5DBLloq+2jGqVgJAZChr5BRDdvRz6sEz8ykLlmMXdC2Urbw2gm211dCLQTnPym+rrbSDEwzGhuHJhJersjDXZ9YjxFRQ5FYAUo8OcFjU3VI3n/yHu4S7fHIDgvIuLheSx9bjA61WtDkbaZ7AWgyUjyh4DWC3dIdPecpSfNSMHa1csWpBVvxxbQ+ciOYjDmXf7WANNMdm6udbhByP2Jzy2YNkdbTzTOjrpaIB9Yk1iqH85k14FXNmFxfZoZKwkK/ACFZzWqZL3xET6Lfo1oqtesM+fDfS7CWdPzFFzOTvp4yPMRW/kCHhpwp5MvVfsYBAsFlyofgLVwRnWo=
