branches:
  only:
  - enable_travis
  - master
  - release
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
matrix:
  include:
  - language: android
    sudo: required
    jdk: oraclejdk8
    before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
    cache:
      directories:
      - "$HOME/.gradle"
      - "$HOME/.android"
      - ".gradle"
    env:
      - RELEASE_BUILD=true
    android:
      components:
      - platform-tools
      - android-28
      - build-tools-28.0.3
      - extra-google-m2repository
      - extra-android-m2repository
      - tools
      licenses:
      - android-sdk-preview-license-.+
      - android-sdk-license-.+
      - google-gdk-license-.+
    before_install:
    - openssl aes-256-cbc -K $encrypted_1701aaafcc71_key -iv $encrypted_1701aaafcc71_iv
      -in .travis/android/google-services.json.enc -out frontend/android/google-services.json
      -d
    - openssl aes-256-cbc -K $encrypted_1701aaafcc71_key -iv $encrypted_1701aaafcc71_iv
      -in .travis/android/droidkaigi2019.keystore.enc -out .release/droidkaigi2019.keystore
      -d
    - "./.travis/android/before_install.bash"
    script: ".travis/android/run.bash"
  - language: objective-c
    os: osx
    osx_image: xcode10.1
    xcode_workspace: frontend/ios/DroidKaigi\ 2019.xcworkspace
    cache:
    - directories:
      - ios/frontend/vendor/bundle
      - ios/frontend/Pods
      - "$HOME/.gradle"
      - "$HOME/.android"
      - ".gradle"
      - "$ANDROID_HOME"
    env:
    - ANDROID_HOME="$HOME/android-sdk"
    before_install:
    - "./.travis/ios/before_install.bash"
    script: ".travis/ios/run.bash"
env:
  global:
  - secure: WaV6+r0/iE0MYpAXa31dqLydcIgcjQpodx2c1wbkZv6GjRBcrOiq94xJr4Mo7Rpctwzvw9JIG362QdyOws3Z7x5UTDL0pOyj+hOl0iTPl6Gqp8wOX9KcO9hIgyuYlce0CWY4uW7URlRXO7/4cuo4Ajn5MGx7n0X+Akte37654RBtfwKfBNpn0+K2nXAV4crPXv+zMZHxn4TDXrk6E8L9pPlLSVGkiAxDPujiKK3v7sCno+DtSok2qP3M+U6TJHSw4bRPyxCE9JrJy+4abTRAhwXt5w9izL4ZKPFNqZH56ubHF/Te0CdiSpKSU1btNCfU2fjLEeUpqhVf3ngzHcBINetfFL3Md5DBLloq+2jGqVgJAZChr5BRDdvRz6sEz8ykLlmMXdC2Urbw2gm211dCLQTnPym+rrbSDEwzGhuHJhJersjDXZ9YjxFRQ5FYAUo8OcFjU3VI3n/yHu4S7fHIDgvIuLheSx9bjA61WtDkbaZ7AWgyUjyh4DWC3dIdPecpSfNSMHa1csWpBVvxxbQ+ciOYjDmXf7WANNMdm6udbhByP2Jzy2YNkdbTzTOjrpaIB9Yk1iqH85k14FXNmFxfZoZKwkK/ACFZzWqZL3xET6Lfo1oqtesM+fDfS7CWdPzFFzOTvp4yPMRW/kCHhpwp5MvVfsYBAsFlyofgLVwRnWo=
  - secure: Ch+CmzyuOzXNmmlII9lacT8J4WjQapV9ft/35qn93l4TMBZENlcz5Z32pN2FuLCioSu4YhhR/50uv3JIndEVp/braTF3jIZIxt16rY1plDfvRNM9CCTfMcyBw5iujkYLnm7lsN0Ly8hEnEJhMJ1OIHC1x9iaXpf1Nkz6eMfA1FnEZWMtyOfVSIrm+2R4b8iqnUdig7zbbpSCdIdLdtGBglOtmQqY+pXu4AnU95iLFCWxUQUaLLtZiWpPzA9DUEtERmTuEX7hBgOVy/r0Eo4NiDg/ktZvosasbx+vqly1ScN8/M78AIolTVrm6mkTA+/CNgQKgoTHzC3nJrR+TKP/gtIQz3P1VNmy8e2OUzfxAhhx5myEtp2++qYfeKNDSPFTZMzPJhszi8c3E7L9hjDMOO/WAX0zs5g8wK2ff9Tqk//ZMi72mp8Z3lTIcHWdg1wgBqeQIrJAyMG2yWilyRf7Xx8rTaSijUqCLwJJnJjbhwd6Vdn7D/woaoUlfzRBosPFkpF3WZcTA/Ame1qRaRdp4/I6ikStIPmB8VHKW8xhYGwvU5YICpNRKXLJ3YK/HXqQfAhiw+Cxw9BMo0GpIp129lzVBoJluEaONn28P4BpQBS8Xdom0Yy0SEOkxRD9bVZy8MBQtLVsSaGSgBPTp5sd+sKOjSxynG0YZUCf75JRN6I=
  - secure: KW+ktEA5/HhTW+JB+eF3dgSIA4K9MJibgd2F1nWezvWY2r3MhqXARMSA3AFwTVrD7ROB3nI//MupNdTQakAPKIB4zgwJUk7EbDZUVoq4hx9yC65XGpaeN/l9DNGJr57pLy+GDHbWuV3mWAOFHKhB/TfT88hIrlkp/5m+/74MJBKUaO2tPvEII+jMIIYy5jx2++FirbYcBaHdJ9jaYso/pHzRnCZJYEWKgyn2VqI+dR7He2Zk/0hOhQXkTV9Gkm5oJwiRz2x2BtFko2ZmolXbL4CjXxKEaQzpNIyyUZrecJE8TBOjnNTdlP4VNR5uZjf1+FRP/yzZNwysUbLd/cjohlOAy6j1MF4x3zuNwKIH06ktM09R5G+Ene9Wi6mJiG+FuL16UYTl6Z1Pj9drBeourhqu8C7HqF1Yhshwo8qsxuM9MAnhl2qt33H2YMzkTw77P32X4t/4QF7ChfN0gQg1JeBMjpvjj0xAyc24u70Iey9ohEmmSbtN4Yq6aYPbuqAZzcbn2IcvUdLQaYQtIr5W1ii+RITFvR6xV4icC0vHiV4foJmWyKdO6VlpQ+PcVpFUeVKm/70Kh0217VQLzly9ib7vo01nQETMNiIHpGFwdnd2yjUuQhlG+67DmS0WCunevRVpsmPV9pED/i/ijaZUwvnw91tc08Td/KBvDge2NN0=
  - secure: wGfIhyZW3K3pMnw2r85e7v7r3Kan8ywYscYZuwtRMNRiLIkG9Nw+BjcdFrGmWJfYWWnk0/MIXT4EvOq3f7y81OSh5NYtnMIXKtvs3iehUS30nvQr1+kIu60NzKnBt8NoYMlnkQbGU3ScicZzlxPSvONr1etYbUhvA20BI6+dX3uaDrxsAcndjJDFFq4bkGbIFfD9iSOIXj7azaVAhTyEPyBGzebbhrWBjqsmx9ocffXtNT/6Qx2qhOrMTxj4Em3LxKpVckZtIOZ23Ta2ZDvDv4JBwRroE1IaDE45mjL5uwhhsq7M7K76EBb8isAmXAuMzFz0mZDYTSxr2/3iPIES99LAhFnqXahbwaAbxHmj4SEzaWWHz6me8t7uuTfI/U8AwcdVT8u9BTdg01/BexPsFb1X751Q/7Or8TlBi0uYFuRPDXp+aBuyQsZEWkQ8o6aX3omxx7ZgA/gSy0cRZU8dykJmRbHfwb81bi2jIcXp4nWsNklAuGCRRF+Sy9bWtolO1HaMcEmbxIlWxvxSM39hh9Cq8MTTDww7sn7RNFLXhsB82fiUyY2DKgUsEJyksqCJI1fBcLQmdfdYYSLQhJaHTIRKasxM1cN08o5i6mxYjvi6ABZYiiWcM68qORs1/XQ+vn4VzkzqgTXxuMBeSD1VaLwafz9Ox9x7hPNScKJjV/w=
